add: docker
Kinoshita0623/Stocklist pull request #1
Opened 2021-04-20 09:17 UTC by yumekiti

dockerの設定を加えました
docker-composeはまだです、

2021-04-20 16:16 UTC, Kinoshita0623 requested changes
docker-comopse.ymlを実装してくださいお願いします

2021-04-20 19:37 UTC, yumekiti commented
動作確認中しばし待たれよ。

2021-04-20 21:19 UTC, Kinoshita0623 requested changes
StocklistLogs以下のファイルはgitignoreしてください。
お願いします。

2021-04-21 01:32 UTC, Kinoshita0623 approved these changes
勝手に修正しておいたぞい

2021-04-21 01:32 UTC, merged