add: AddSpa
Kinoshita0623/Stocklist pull request #97
Opened 2021-05-27 06:45 UTC by yumekiti

多分動くよ。

2021-05-27 06:45 UTC, yumekiti commented
動作未確認

2021-05-27 08:11 UTC, Kinoshita0623 requested changes
二重にバリデーションをしてしまっているので、そこのところの修正お願いします。

2021-05-27 08:11 UTC, Kinoshita0623 commented on src/app/Http/Controllers/Api/UserController.php
> +        $credentials = $request->validate([
LoginUserRequestを利用しているのでこのバリデーションは不要だと思います。

2021-05-28 07:28 UTC, Kinoshita0623 approved these changes
LGTM

2021-05-28 07:28 UTC, merged